### ISSUE TITLE
How does this solver perform on large sparse problems?

### ISSUE THREAD

**Issue by MatthewPeterKelly** [liuq/QuadProgpp#1]
I'm interested in solving trajectory optimization problems. In general, these problems are reduced to large sparse constrained optimization problems. Question:  How does your code perform on large sparse problems? The problems that I'm interested in have:

- x is of length 50 - 300  (decision variables)
- g0 is [0]
- G is diagonal  (least squares)
- CE has a maximum of 2-4 non-zero elements per row (collocation constraints)
- CI has a maximum of 1 non-zero element per row (limits on decision variables)

```
min 0.5 * x G x + g0 x
s.t.
    CE^T x + ce0 = 0
    CI^T x + ci0 >= 0
```

**Comment by liuq** [comment]
Hi,

no idea. In principle the method should scale well, but I used the method
with some 20-30 decision variables and I have no direct experience with
bigger problem sizes.

Needless to say that the matrix implementation is a dense one, it would be
valuable to support also sparse representations, but I will not have the
time for it (any contribution is welcome).

All the best,

Luca
Il giorno ven 28 ott 2016 alle 14:52 Matthew Kelly <notifications@github.com>
ha scritto:

**Comment by MatthewPeterKelly** [comment]
Thanks for the quick response! 

That all sounds reasonable. I'll let you know if I get a chance to use this code to solve a sparse problem.

This looks great for solving dense problems - I shared this page with some friends who were looking for a good open-source QP solver.
