### ISSUE TITLE
function call issue

### ISSUE THREAD

**Issue by vissa7** [liuq/QuadProgpp#10]
Everything works fine but when trying to call solve_quadprog(with the arguments) an error pops up “unidentified reference to...”, even in the example code uploaded. Any solution for this?

**Comment by liuq** [comment]
Can you provide more context? (Operating System, compiler, etc.)

Also the full description of the error could helpful.

**Comment by vissa7** [comment]
IDE: Dev C++
PC: 64-bit, running windows 10
Error: “Unidentified reference to quadprogpp::solve_quadprog(quadprogg::Matrix<double>&,...), including all the arguments io the prototype.

Thanks for the quick support, sorry for wasting your time...

**Comment by liuq** [comment]
This is a linking problem, this means that the quadprog library do not link with the executable. Did you create a makefile through cmake or just compile it in Dev C++?

**Comment by liuq** [comment]
Unfortunately I can't help more, I am not a Dev C++ user and this has to deal with the use of the tool. I suggest to read something about library linking in Dev C++.

**Comment by vissa7** [comment]
Ok man, thank you very much!!
