### ISSUE TITLE
The operator  "*" of matrix is not correct, in Array.h

### ISSUE THREAD

**Issue by JevyLee** [liuq/QuadProgpp#14]
i'm confusing about the following code.
"template <typename T>
Matrix<T> operator*(const Matrix<T>& lhs, const Matrix<T>& rhs)
{
  if (lhs.ncols() != rhs.ncols() || lhs.nrows() != rhs.nrows())
    throw std::logic_error("Operator*: matrices have different sizes");
  Matrix<T> tmp(lhs.nrows(), lhs.ncols());
  for (unsigned int i = 0; i < lhs.nrows(); i++)
    for (unsigned int j = 0; j < lhs.ncols(); j++)
      tmp[i][j] = lhs[i][j] * rhs[i][j];
        
  return tmp;
}"
The operator "*" of matrix is not correct.

**Comment by liuq** [comment]
Indeed it's not a matrix multiplication but a element-wise multiplication.

**Comment by JevyLee** [comment]
thanks for your quick response.
