### ISSUE TITLE
wrong value and Cholesky decomposition

### ISSUE THREAD

**Issue by smart-duoduopi** [liuq/QuadProgpp#15]
I did some tests about the solver and found out that the accuracy of the solution is low .What is more, because of Cholesky decomposition, a lot of quadprog problem can not be solved. Maybe it is only useful for symmetrical positive determined matrix problem.

**Comment by liuq** [comment]
It seems you didn’t read Goldfarb and Idnani paper about the
hypothesis behind the algorithm. Indeed it works only for Definite
Quadratic Programming problems.

On 3 settembre 2019 a 09:28:03, Jiaxin Gao (notifications@github.com) scritto:

**Comment by smart-duoduopi** [comment]
thanks for your reply
