### ISSUE TITLE
Optimal Solution Found Exit

### ISSUE THREAD

**Issue by Jcw17** [liuq/QuadProgpp#21]
Seldom coming across ss >= 0.0 's exit judgement is not satisfied.
And ss is about -e-13 about. and could not converge anymore.
For anyone who has strucked in the loop for that, Change ss >= threshould (any number can satisfy your need, like -1e-6) would work.

**Comment by santoshj1989** [comment]
This was quite helpful, you've nailed the exact location where I had an issue. Thanks!
